<?php

require_once 'vendor/autoload.php';

// Initialize Laravel application
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Letter;
use App\Models\LetterTemplate;

try {
    echo "=== DEBUGGING CURRENT ISSUE ===\n";
    
    // Check the latest letter from the logs
    $latestLetter = Letter::where('letter_reference', 'LTR/2025/07/00321123')->first();
    
    if ($latestLetter) {
        echo "Latest letter from logs (ID: " . $latestLetter->id . "):\n";
        echo "Reference: " . $latestLetter->letter_reference . "\n";
        echo "Subject: " . $latestLetter->letter_subject . "\n";
        echo "Content: " . substr($latestLetter->letter_content, 0, 100) . "...\n";
        echo "Recipient: " . ($latestLetter->letter_data['recipient_name'] ?? 'NULL') . "\n";
        echo "PDF Path: " . $latestLetter->letter_file_path . "\n";
        
        // Check if PDF exists
        $pdfPath = public_path('letters/' . basename($latestLetter->letter_file_path));
        echo "PDF File Path: " . $pdfPath . "\n";
        echo "PDF Exists: " . (file_exists($pdfPath) ? 'YES' : 'NO') . "\n";
        
        if (file_exists($pdfPath)) {
            echo "PDF Size: " . filesize($pdfPath) . " bytes\n";
        }
        
        // Check database data integrity
        echo "\nFull letter data:\n";
        print_r($latestLetter->toArray());
        
        // Check template
        $template = LetterTemplate::find($latestLetter->template_id);
        if ($template) {
            echo "\nTemplate data:\n";
            echo "Template Name: " . $template->template_name . "\n";
            echo "Template Variables: " . json_encode($template->template_variables) . "\n";
        }
        
    } else {
        echo "Letter with reference LTR/2025/07/00321123 not found\n";
    }
    
    echo "\n=== CHECKING ARCHIVE PAGE DATA ===\n";
    
    // Check the latest 3 letters to see what archive page would show
    $letters = Letter::latest()->limit(3)->get();
    
    foreach ($letters as $letter) {
        echo "\nLetter ID: " . $letter->id . "\n";
        echo "  Reference: " . $letter->letter_reference . "\n";
        echo "  Subject: " . $letter->letter_subject . "\n";
        echo "  Recipient: " . ($letter->letter_data['recipient_name'] ?? 'NULL') . "\n";
        echo "  Generated by: " . ($letter->letter_data['generated_by_name'] ?? 'NULL') . "\n";
        echo "  PDF Path: " . ($letter->letter_file_path ?? 'NULL') . "\n";
        echo "  PDF Exists: " . (file_exists(public_path('letters/' . basename($letter->letter_file_path))) ? 'YES' : 'NO') . "\n";
    }
    
    echo "\n=== CHECKING WHAT'S ACTUALLY IN THE PDF ===\n";
    
    // Let's try to read the PDF content (basic check)
    if (isset($pdfPath) && file_exists($pdfPath)) {
        $pdfContent = file_get_contents($pdfPath);
        echo "PDF file size: " . strlen($pdfContent) . " bytes\n";
        
        // Check if it's a valid PDF
        if (substr($pdfContent, 0, 4) === '%PDF') {
            echo "PDF format: VALID\n";
        } else {
            echo "PDF format: INVALID\n";
        }
        
        // Try to check if PDF contains text content
        $textContent = '';
        if (function_exists('iconv')) {
            $textContent = @iconv('UTF-8', 'UTF-8//IGNORE', $pdfContent);
        }
        
        if (strpos($textContent, $latestLetter->letter_subject) !== false) {
            echo "PDF contains subject: YES\n";
        } else {
            echo "PDF contains subject: NO\n";
        }
        
        if (strpos($textContent, $latestLetter->letter_content) !== false) {
            echo "PDF contains content: YES\n";
        } else {
            echo "PDF contains content: NO\n";
        }
    }
    
    echo "\n=== MANUAL TEMPLATE TEST ===\n";
    
    // Let's manually test template rendering
    if ($latestLetter && $template) {
        $data = [
            'letter' => $latestLetter,
            'template' => $template,
            'gd_available' => false
        ];
        
        try {
            $html = view('letters.pdf-template', $data)->render();
            echo "Template renders: YES\n";
            echo "HTML length: " . strlen($html) . " chars\n";
            
            // Check if key content is in the HTML
            if (strpos($html, $latestLetter->letter_subject) !== false) {
                echo "HTML contains subject: YES\n";
            } else {
                echo "HTML contains subject: NO\n";
            }
            
            if (strpos($html, $latestLetter->letter_content) !== false) {
                echo "HTML contains content: YES\n";
            } else {
                echo "HTML contains content: NO\n";
            }
            
        } catch (Exception $e) {
            echo "Template render error: " . $e->getMessage() . "\n";
        }
    }
    
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
    echo "Trace: " . $e->getTraceAsString() . "\n";
}