<?php

require_once 'vendor/autoload.php';

$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Letter;
use App\Models\LetterTemplate;
use Barryvdh\DomPDF\Facade\Pdf;

echo "=== PDF GENERATION TEST ===\n\n";

// Get the specific letter
$letter = Letter::find(3);
$template = LetterTemplate::find($letter->template_id);

echo "Creating test PDF with simple content...\n";

// Create a simple test HTML
$testHtml = "
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Test PDF</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .test-section { margin: 20px 0; padding: 10px; border: 1px solid #ccc; }
    </style>
</head>
<body>
    <h1>PDF Generation Test</h1>
    
    <div class='test-section'>
        <h2>Letter Data Test</h2>
        <p><strong>Reference:</strong> " . $letter->letter_reference . "</p>
        <p><strong>Subject:</strong> " . $letter->letter_subject . "</p>
        <p><strong>Content:</strong> " . $letter->letter_content . "</p>
        <p><strong>Date:</strong> " . $letter->letter_date->format('d F Y') . "</p>
    </div>
    
    <div class='test-section'>
        <h2>Letter Data JSON Test</h2>
        <p><strong>Recipient Name:</strong> " . ($letter->letter_data['recipient_name'] ?? 'NULL') . "</p>
        <p><strong>Recipient Address:</strong> " . ($letter->letter_data['recipient_address'] ?? 'NULL') . "</p>
        <p><strong>Generated By:</strong> " . ($letter->letter_data['generated_by_name'] ?? 'NULL') . "</p>
        <p><strong>Position:</strong> " . ($letter->letter_data['generated_by_position'] ?? 'NULL') . "</p>
    </div>
    
    <div class='test-section'>
        <h2>Template Test</h2>
        <p><strong>Template Name:</strong> " . ($template->template_name ?? 'NULL') . "</p>
        <p><strong>Has Header Image:</strong> " . (isset($template->template_variables['header_image']) ? 'YES' : 'NO') . "</p>
        <p><strong>Has Footer Image:</strong> " . (isset($template->template_variables['footer_image']) ? 'YES' : 'NO') . "</p>
    </div>
</body>
</html>
";

// Generate PDF
$pdf = Pdf::loadHTML($testHtml);
$pdf->setPaper('A4', 'portrait');

$testPdfPath = public_path('letters/TEST_PDF_' . time() . '.pdf');
$pdf->save($testPdfPath);

echo "Test PDF generated: " . $testPdfPath . "\n";
echo "File size: " . filesize($testPdfPath) . " bytes\n";

// Now let's test with the actual template
echo "\n=== TESTING ACTUAL TEMPLATE ===\n";

$data = [
    'letter' => $letter,
    'template' => $template,
    'gd_available' => true
];

try {
    $pdf2 = Pdf::loadView('letters.pdf-template', $data);
    $pdf2->setPaper('A4', 'portrait');
    
    $actualPdfPath = public_path('letters/ACTUAL_TEST_' . time() . '.pdf');
    $pdf2->save($actualPdfPath);
    
    echo "Actual template PDF generated: " . $actualPdfPath . "\n";
    echo "File size: " . filesize($actualPdfPath) . " bytes\n";
    
} catch (\Exception $e) {
    echo "Error generating PDF with actual template: " . $e->getMessage() . "\n";
}

?>