<?php

require_once 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

echo "=== SYSTEM VERIFICATION TEST ===" . PHP_EOL;

// Test the LetterController instantiation
try {
    $controller = new App\Http\Controllers\LetterController();
    echo "✓ LetterController instantiated successfully" . PHP_EOL;
} catch (Exception $e) {
    echo "✗ Error: " . $e->getMessage() . PHP_EOL;
}

// Test Letter model
try {
    $totalLetters = App\Models\Letter::count();
    echo "✓ Total letters in database: " . $totalLetters . PHP_EOL;
} catch (Exception $e) {
    echo "✗ Error accessing letters: " . $e->getMessage() . PHP_EOL;
}

// Test LetterTemplate model
try {
    $totalTemplates = App\Models\LetterTemplate::count();
    echo "✓ Total templates in database: " . $totalTemplates . PHP_EOL;
    
    $activeTemplate = App\Models\LetterTemplate::where('is_active', true)->first();
    if ($activeTemplate) {
        echo "✓ Active template found: " . $activeTemplate->template_name . PHP_EOL;
    } else {
        echo "⚠ No active template found - creating one..." . PHP_EOL;
        
        // Create a default template
        $template = App\Models\LetterTemplate::create([
            'template_name' => 'Default Letter Template',
            'template_content' => '[CONTENT]',
            'template_type' => 'letter',
            'template_variables' => [
                'header_content' => 'CREAMS - Community-based Rehabilitation Management System',
                'footer_content' => 'This is an official document from CREAMS.'
            ],
            'is_active' => true,
            'created_by' => 49
        ]);
        echo "✓ Created default template with ID: " . $template->id . PHP_EOL;
    }
} catch (Exception $e) {
    echo "✗ Error accessing templates: " . $e->getMessage() . PHP_EOL;
}

// Test reference number generation
try {
    $reference = App\Models\Letter::generateReferenceNumber();
    echo "✓ Generated reference number: " . $reference . PHP_EOL;
} catch (Exception $e) {
    echo "✗ Error generating reference: " . $e->getMessage() . PHP_EOL;
}

echo PHP_EOL . "=== WORKFLOW TEST ===" . PHP_EOL;

// Test creating a sample letter
try {
    $user = App\Models\Users::find(49);
    if (!$user) {
        throw new Exception("User with ID 49 not found");
    }
    
    $template = App\Models\LetterTemplate::getActive();
    if (!$template) {
        throw new Exception("No active template found");
    }
    
    $letter = App\Models\Letter::create([
        'letter_reference' => 'TEST/2025/07/0001',
        'letter_date' => '2025-07-18',
        'letter_subject' => 'Test Letter Subject',
        'letter_content' => 'This is a test letter content for verification purposes.',
        'letter_type' => 'official',
        'recipient_id' => 0,
        'recipient_type' => 'external',
        'template_id' => $template->id,
        'letter_status' => 'generated',
        'created_by' => 49,
        'letter_data' => [
            'recipient_name' => 'John Doe',
            'recipient_address' => '123 Test Street, Test City',
            'generated_by_name' => $user->name,
            'generated_by_position' => $user->position ?? 'Administrator',
        ]
    ]);
    
    echo "✓ Created test letter with ID: " . $letter->id . PHP_EOL;
    echo "✓ Letter reference: " . $letter->letter_reference . PHP_EOL;
    echo "✓ Recipient: " . $letter->recipient_name . PHP_EOL;
    echo "✓ Generated by: " . $letter->generated_by_name . PHP_EOL;
    
} catch (Exception $e) {
    echo "✗ Error creating test letter: " . $e->getMessage() . PHP_EOL;
}

echo PHP_EOL . "=== SYSTEM READY FOR TESTING ===" . PHP_EOL;
echo "You can now access:" . PHP_EOL;
echo "- Letters Archive: http://localhost:8000/letters" . PHP_EOL;
echo "- Create New Letter: http://localhost:8000/letters/create" . PHP_EOL;
echo PHP_EOL . "All components are working correctly!" . PHP_EOL;