/**
 * Playwright Global Setup
 *
 * Pre-authenticates all roles once before the test suite starts.
 * Saves browser session cookies (Laravel PHPSESSID) to .auth/*.json files.
 *
 * Uses Playwright's lightweight request API (no browser) for authentication.
 * This makes only 2 HTTP requests per session (GET /login for CSRF token,
 * POST /login to authenticate), skipping Chromium and dashboard rendering
 * entirely.  This keeps global-setup fast and reliable under single-threaded
 * PHP dev-server load.
 *
 * Two sets of auth files are created:
 *   Primary (admin.json etc.)  — used by dashboard, RBAC, functional tests.
 *                                 These sessions are NEVER invalidated.
 *   Logout  (admin-2.json etc.)— used ONLY by logout.spec.ts.
 *                                 These sessions are intentionally invalidated
 *                                 during logout testing.
 *
 * Keeping the two sets separate ensures that logout tests cannot break
 * the sessions relied upon by the rest of the suite.
 */

import { request, FullConfig } from '@playwright/test';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { execSync } from 'node:child_process';

// UAT credentials produced by database/seeders/UATSeeder.php (sprint May 2026).
// Old TestingGuideDataSeeder credentials (lakshmi.krishnan@iium.edu.my, etc.) no
// longer exist after migrate:fresh --seeder=UATSeeder. Re-seed UAT data via
// `php artisan db:seed --class=UATSeeder` if these accounts are missing.
const ROLES = [
  { name: 'admin',      email: 'super.admin@uat.creams.test',  password: 'UatPass2026!' },
  { name: 'supervisor', email: 'supervisor.a1@uat.creams.test', password: 'UatPass2026!' },
  { name: 'teacher',    email: 'teacher.a1@uat.creams.test',    password: 'UatPass2026!' },
  { name: 'ajk',        email: 'ajk.a1@uat.creams.test',        password: 'UatPass2026!' },
];

async function authenticate(role: { name: string; email: string; password: string }, authDir: string, suffix = '') {
  // Playwright request context — no browser, no rendering overhead.
  // Cookies (including laravel_session) are tracked automatically.
  const apiContext = await request.newContext({
    baseURL: 'http://localhost:8000',
    ignoreHTTPSErrors: true,
  });

  // Step 1: GET /auth/login to obtain the CSRF token embedded in the Blade form.
  const loginPageResponse = await apiContext.get('/auth/login');
  const html = await loginPageResponse.text();

  // Extract the hidden _token field generated by the @csrf Blade directive.
  const tokenMatch = /name="_token"\s+value="([^"]+)"/.exec(html);
  if (!tokenMatch) {
    await apiContext.dispose();
    throw new Error(`CSRF token not found in login page for ${role.name}`);
  }

  // Step 2: POST /auth/check with credentials and CSRF token.
  //
  // Why /auth/check (not /login): the login Blade form uses
  //   action="{{ route('auth.check') }}" → POST /auth/check
  // POST /login returns 405 Method Not Allowed.
  //
  // Why we include both 'identifier' and 'email':
  //   The throttle:login middleware keys on $request->input('email') ?: $request->ip()
  //   Without 'email', all 8 logins share the same IP key and hit the 5/min limit
  //   on attempt 6 (throttled → redirect back to /login → timeout).
  //   Including 'email' gives each user their own rate-limit bucket (2 logins each,
  //   well under the 5/min per-user cap).
  const loginResponse = await apiContext.post('/auth/check', {
    form: {
      _token: tokenMatch[1],
      identifier: role.email,
      email: role.email,       // sets per-user throttle key (avoids IP-level rate limit)
      password: role.password,
    },
  });

  // After following the redirect, verify we're not back on /auth/login or /auth/check.
  const finalUrl = loginResponse.url();
  if (finalUrl.includes('/auth/login') || finalUrl.includes('/auth/check')) {
    await apiContext.dispose();
    throw new Error(
      `Login failed for ${role.name}: redirected back to ${finalUrl} (HTTP ${loginResponse.status()})`
    );
  }

  // Save the authenticated session cookies to .auth/<name>.json (or .auth/<name>-2.json).
  const filename = suffix ? `${role.name}-${suffix}.json` : `${role.name}.json`;
  await apiContext.storageState({ path: path.join(authDir, filename) });
  await apiContext.dispose();
}

async function globalSetup(config: FullConfig) {
  console.log('\nGlobal setup: Pre-authenticating all roles...');

  // Force-delete soft-deleted and live test trainees so the trainee_id sequential
  // generator does not collide with records left over from prior test runs.
  // (Trainee uses SoftDeletes; the generator only scans non-deleted rows, so
  //  soft-deleted rows can still cause unique-key violations on trainee_id.)
  const projectRoot = path.resolve(__dirname, '..', '..');
  try {
    execSync(
      `php artisan tinker --execute="App\\Models\\Trainee::withTrashed()->where('trainee_email','LIKE','test.trainee.%@test.com')->forceDelete();"`,
      { cwd: projectRoot, stdio: 'pipe' }
    );
    console.log('  Cleared test trainees from previous runs.\n');
  } catch {
    console.warn('  Warning: test trainee cleanup skipped (non-fatal).\n');
  }

  const authDir = path.join(__dirname, '.auth');
  if (!fs.existsSync(authDir)) {
    fs.mkdirSync(authDir, { recursive: true });
  }

  // Primary sessions — used by dashboard, RBAC, and functional tests
  for (const role of ROLES) {
    console.log(`  Authenticating ${role.name} (primary)...`);
    await authenticate(role, authDir);
    console.log(`  ✓ ${role.name} authenticated`);
  }

  // Logout sessions — used exclusively by logout.spec.ts
  // These will be invalidated during testing; primary sessions stay clean.
  for (const role of ROLES) {
    console.log(`  Authenticating ${role.name} (logout set)...`);
    await authenticate(role, authDir, '2');
    console.log(`  ✓ ${role.name}-2 authenticated`);
  }

  console.log('Global setup complete: 8 sessions ready (4 primary + 4 logout)\n');
}

export default globalSetup;
