<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Centre;
use App\Models\User;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Letter>
 */
class LetterFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Ensure centre and user exist
        $centre = Centre::firstOrCreate(
            ['centre_id' => '01'],
            [
                'centre_name' => 'Test Centre',
                'centre_phone' => '+60123456789',
                'centre_email' => 'test@centre.com',
                'centre_capacity' => 50,
                'centre_status' => 'active',
                'is_active' => true,
            ]
        );

        $creator = User::factory()->admin()->create(['centre_id' => $centre->centre_id]);

        // Generate Malaysian address format
        $recipientAddress = fake()->streetAddress() . ', ' .
                          fake()->numerify('#####') . ' ' .
                          fake()->city() . ', ' .
                          fake()->randomElement(['Johor', 'Kedah', 'Kelantan', 'Selangor', 'Kuala Lumpur']);

        return [
            'letter_id' => null, // Will be auto-generated by model
            'letter_name' => fake()->catchPhrase() . ' Letter',
            'letter_date' => fake()->dateTimeBetween('-6 months', 'now'),
            'letter_title' => fake()->sentence(6),
            'letter_subject' => fake()->sentence(8),
            'subject' => fake()->sentence(8),
            'letter_content' => fake()->paragraphs(3, true),
            'content' => fake()->paragraphs(3, true),
            'letter_type' => fake()->randomElement(['official', 'invitation', 'notification', 'certificate', 'report']),
            'recipient_id' => 0, // Default value for factory, can be overridden
            'recipient_name' => fake()->name(),
            'recipient_email' => fake()->optional()->safeEmail(),
            'recipient_address' => $recipientAddress,
            'recipient_type' => fake()->randomElement(['parent', 'guardian', 'organization', 'ministry', 'sponsor']),
            'template_id' => null,
            'letter_status' => 'draft',
            'status' => 'draft',
            'sent_at' => null,
            'is_sent' => false,
            'date_created' => now(),
            'date_sent' => null,
            'letter_file_path' => null,
            'pdf_path' => null,
            'pdf_filename' => null,
            'pdf_file_size' => null,
            'file_size_bytes' => null,
            'generated_file_type' => 'pdf',
            'generated_at' => now(),
            'letter_data' => [
                'recipient_name' => fake()->name(),
                'generated_by_name' => $creator->name,
                'generated_by_position' => fake()->randomElement(['Director', 'Manager', 'Administrator', 'Supervisor']),
            ],
            'generation_metadata' => null,
            'notes' => fake()->optional()->sentence(),
            'centre_id' => $centre->centre_id,
            'created_by' => $creator->id,
            'generated_by' => $creator->id,
        ];
    }

    /**
     * Indicate that the letter is a draft
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'letter_status' => 'draft',
            'status' => 'draft',
            'is_sent' => false,
            'date_sent' => null,
        ]);
    }

    /**
     * Indicate that the letter is sent
     */
    public function sent(): static
    {
        return $this->state(fn (array $attributes) => [
            'letter_status' => 'sent',
            'status' => 'sent',
            'is_sent' => true,
            'date_sent' => fake()->dateTimeBetween('-1 month', 'now'),
            'sent_at' => fake()->dateTimeBetween('-1 month', 'now'),
        ]);
    }

    /**
     * Indicate that the letter is official
     */
    public function official(): static
    {
        return $this->state(fn (array $attributes) => [
            'letter_type' => 'official',
        ]);
    }

    /**
     * Indicate that the letter is for a parent/guardian
     */
    public function toParent(): static
    {
        return $this->state(fn (array $attributes) => [
            'recipient_type' => 'parent',
        ]);
    }
}
