@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <!-- Page Header -->
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="page-title">
                    <i class="fas fa-file-alt mr-2"></i>Letter Archive
                </h2>
                <div>
                    <a href="/profile#letters-tab" class="btn btn-primary">
                        <i class="fas fa-plus mr-2"></i>Generate New Letter
                    </a>
                    <a href="{{ route('dashboard') }}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left mr-2"></i>Back to Dashboard
                    </a>
                </div>
            </div>

            <!-- Search Bar -->
            <div class="card mb-4">
                <div class="card-body">
                    <form method="GET" action="{{ route('letters.index') }}" class="form-inline">
                        <div class="form-group mr-3">
                            <input type="text" 
                                   name="search" 
                                   class="form-control" 
                                   placeholder="Search by reference or subject..." 
                                   value="{{ request('search') }}"
                                   style="width: 300px;">
                        </div>
                        <button type="submit" class="btn btn-info mr-2">
                            <i class="fas fa-search"></i> Search
                        </button>
                        @if(request('search'))
                            <a href="{{ route('letters.index') }}" class="btn btn-secondary">
                                <i class="fas fa-times"></i> Clear
                            </a>
                        @endif
                    </form>
                </div>
            </div>

            <!-- Letter Table -->
            <div class="card">
                <div class="card-body">
                    @if($letters->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Reference</th>
                                        <th>Subject</th>
                                        <th>Recipient</th>
                                        <th>Date</th>
                                        <th>Generated By</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($letters as $letter)
                                        @php
                                            // Ensure letter_data is properly decoded
                                            $letterData = $letter->letter_data;
                                            if (is_string($letterData)) {
                                                $letterData = json_decode($letterData, true) ?: [];
                                            }
                                            if (!is_array($letterData)) {
                                                $letterData = [];
                                            }
                                        @endphp
                                        <tr>
                                            <td>
                                                <strong>{{ $letter->letter_reference ?? 'N/A' }}</strong>
                                            </td>
                                            <td>{{ Str::limit($letter->letter_subject ?? 'No Subject', 40) }}</td>
                                            <td>{{ $letterData['recipient_name'] ?? 'Unknown' }}</td>
                                            <td>{{ $letter->letter_date ? date('d M Y', strtotime($letter->letter_date)) : 'N/A' }}</td>
                                            <td>
                                                {{ $letterData['generated_by_name'] ?? 'Unknown' }}
                                                <br>
                                                <small class="text-muted">
                                                    {{ $letter->created_at ? $letter->created_at->format('d M Y, h:i A') : '' }}
                                                </small>
                                            </td>
                                            <td>
                                                @if($letter->letter_file_path)
                                                    <span class="badge badge-success">
                                                        <i class="fas fa-check-circle"></i> PDF Ready
                                                    </span>
                                                @else
                                                    <span class="badge badge-warning">
                                                        <i class="fas fa-exclamation-circle"></i> No PDF
                                                    </span>
                                                @endif
                                            </td>
                                            <td>
                                                @if($letter->letter_file_path)
                                                    <a href="{{ route('profile.letter.download', $letter->id) }}" 
                                                       class="btn btn-sm btn-primary" 
                                                       title="Download PDF">
                                                        <i class="fas fa-download"></i>
                                                    </a>
                                                @endif
                                                
                                                @if(session('role') === 'admin' || $letter->created_by === session('id'))
                                                    <button type="button" 
                                                            class="btn btn-sm btn-danger delete-letter-btn" 
                                                            data-id="{{ $letter->id }}"
                                                            data-reference="{{ $letter->letter_reference }}"
                                                            title="Delete">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                        <!-- Pagination -->
                        <div class="mt-3">
                            {{ $letters->appends(request()->query())->links() }}
                        </div>
                    @else
                        <div class="text-center py-5">
                            <i class="fas fa-inbox fa-3x text-muted mb-3"></i>
                            <h5>No Letter Found</h5>
                            <p class="text-muted">
                                @if(request('search'))
                                    No letters match your search criteria.
                                @else
                                    You haven't generated any letters yet.
                                @endif
                            </p>
                            <a href="/profile#letters-tab" class="btn btn-primary mt-3">
                                <i class="fas fa-plus mr-2"></i>Generate Your First Letter
                            </a>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this letter?</p>
                <p><strong>Reference: <span id="deleteReference"></span></strong></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(document).ready(function() {
    var deleteId = null;
    
    // Delete button click
    $('.delete-letter-btn').on('click', function() {
        deleteId = $(this).data('id');
        var reference = $(this).data('reference');
        $('#deleteReference').text(reference);
        $('#deleteModal').modal('show');
    });

    // Confirm delete
    $('#confirmDelete').on('click', function() {
        if (!deleteId) return;

        $.ajax({
            url: '/letters/' + deleteId,
            type: 'DELETE',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Failed to delete letter');
                }
            },
            error: function() {
                alert('Error deleting letter');
            }
        });
    });
});
</script>
@endpush