@extends('layouts.app')

@section('title', 'Letter Details - CREAMS')

@section('content')
<div class="letter-detail-container">
    <div class="page-header">
        <div>
            <h1 class="page-title">Letter Details</h1>
            <p class="subtitle">{{ $letter->letter_id }}</p>
        </div>
        <div class="page-actions">
            <a href="{{ route('letters.download', $letter->id) }}" class="btn btn-success">
                <i class="fas fa-download"></i> Download PDF
            </a>
            <a href="{{ route('letters.dashboard') }}" class="btn btn-outline-secondary">
                <i class="fas fa-arrow-left"></i> Back to Letters
            </a>
        </div>
    </div>

    {{-- Flash Message --}}
    @if(session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="fas fa-check-circle mr-2"></i> {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if(session('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="fas fa-exclamation-circle mr-2"></i> {{ session('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-lg-8">
            {{-- Letter Content Card --}}
            <div class="letter-card">
                <div class="letter-card-header">
                    <h3>Letter Content</h3>
                    <span class="badge badge-primary">{{ ucfirst($letter->letter_status) }}</span>
                </div>
                <div class="letter-card-body">
                    <div class="letter-content">
                        <div class="letterhead">
                            <h4>{{ $letter->letter_subject }}</h4>
                            <p class="date">Date: {{ $letter->letter_date ? Carbon\Carbon::parse($letter->letter_date)->format('F j, Y') : 'N/A' }}</p>
                        </div>
                        
                        <div class="recipient-info">
                            <strong>To:</strong><br>
                            {{ $letter->letter_data['recipient_name'] ?? 'N/A' }}<br>
                            {!! nl2br(e($letter->letter_data['recipient_address'] ?? '')) !!}
                        </div>
                        
                        <div class="letter-body">
                            {!! nl2br(e($letter->letter_content)) !!}
                        </div>
                        
                        <div class="signature">
                            <p>Sincerely,</p>
                            <p><strong>{{ $letter->letter_data['sender_name'] ?? session('name') }}</strong><br>
                            {{ ucfirst($letter->letter_data['sender_role'] ?? session('role')) }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            {{-- Letter Information Card --}}
            <div class="info-card">
                <div class="info-card-header">
                    <h3>Letter Information</h3>
                </div>
                <div class="info-card-body">
                    <div class="info-item">
                        <label>Reference Number:</label>
                        <span>{{ $letter->letter_id }}</span>
                    </div>
                    <div class="info-item">
                        <label>Subject:</label>
                        <span>{{ $letter->letter_subject }}</span>
                    </div>
                    <div class="info-item">
                        <label>Date:</label>
                        <span>{{ $letter->letter_date ? Carbon\Carbon::parse($letter->letter_date)->format('M j, Y') : 'N/A' }}</span>
                    </div>
                    <div class="info-item">
                        <label>Generated By:</label>
                        <span>{{ $letter->letter_data['sender_name'] ?? session('name') }}</span>
                    </div>
                    <div class="info-item">
                        <label>Template:</label>
                        <span>{{ $letter->template ? $letter->template->template_name : 'Default' }}</span>
                    </div>
                    <div class="info-item">
                        <label>Created:</label>
                        <span>{{ $letter->created_at->format('M j, Y g:i A') }}</span>
                    </div>
                    @if($letter->updated_at != $letter->created_at)
                        <div class="info-item">
                            <label>Last Updated:</label>
                            <span>{{ $letter->updated_at->format('M j, Y g:i A') }}</span>
                        </div>
                    @endif
                </div>
            </div>

            {{-- Actions Card --}}
            <div class="actions-card mt-4">
                <div class="actions-card-header">
                    <h3>Actions</h3>
                </div>
                <div class="actions-card-body">
                    <a href="{{ route('letters.download', $letter->id) }}" class="action-item">
                        <i class="fas fa-download"></i>
                        <span>Download PDF</span>
                    </a>
                    <a href="{{ route('letters.dashboard') }}" class="action-item">
                        <i class="fas fa-list"></i>
                        <span>Back to Letters</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('styles')
<style>
.letter-detail-container {
    max-width: 1200px;
    margin: 0 auto;
}

.page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 1px solid #e9ecef;
}

.page-title {
    font-size: 2rem;
    font-weight: 600;
    color: #2c3e50;
    margin: 0;
}

.subtitle {
    color: #6c757d;
    margin: 0;
    font-size: 1.1rem;
}

.letter-card, .info-card, .actions-card {
    background: white;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    margin-bottom: 25px;
    overflow: hidden;
}

.letter-card-header, .info-card-header, .actions-card-header {
    background: linear-gradient(135deg, #007bff, #6c757d);
    color: white;
    padding: 15px 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.letter-card-body, .info-card-body, .actions-card-body {
    padding: 25px;
}

.letter-content {
    font-family: 'Georgia', serif;
    line-height: 1.8;
}

.letterhead {
    text-align: center;
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 2px solid #007bff;
}

.letterhead h4 {
    color: #2c3e50;
    margin-bottom: 10px;
}

.recipient-info {
    margin: 30px 0;
    padding: 15px;
    background: #f8f9fa;
    border-left: 4px solid #007bff;
}

.letter-body {
    margin: 30px 0;
    min-height: 200px;
}

.signature {
    margin-top: 40px;
    text-align: right;
}

.info-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 0;
    border-bottom: 1px solid #f8f9fa;
}

.info-item:last-child {
    border-bottom: none;
}

.info-item label {
    font-weight: 600;
    color: #495057;
    margin: 0;
}

.info-item span {
    color: #6c757d;
    text-align: right;
    max-width: 60%;
}

.action-item {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 12px 0;
    color: #495057;
    text-decoration: none;
    border-bottom: 1px solid #f8f9fa;
    transition: all 0.3s ease;
    background: none;
    border: none;
    width: 100%;
    text-align: left;
}

.action-item:last-child {
    border-bottom: none;
}

.action-item:hover {
    color: #007bff;
    text-decoration: none;
    padding-left: 10px;
}

.action-item.text-danger:hover {
    color: #dc3545;
}

.btn {
    border-radius: 8px;
    padding: 10px 16px;
    font-weight: 600;
    transition: all 0.3s ease;
}

.badge {
    padding: 8px 12px;
    border-radius: 20px;
    font-weight: 600;
    font-size: 0.85rem;
}

@media (max-width: 768px) {
    .page-header {
        flex-direction: column;
        align-items: flex-start;
    }
    
    .page-actions {
        margin-top: 15px;
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
    }
    
    .info-item {
        flex-direction: column;
        align-items: flex-start;
        gap: 5px;
    }
    
    .info-item span {
        max-width: 100%;
        text-align: left;
    }
}
</style>
@endsection

@section('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Auto-hide alerts after 5 seconds
    setTimeout(function() {
        const alerts = document.querySelectorAll('.alert-dismissible');
        alerts.forEach(alert => {
            if (alert.classList.contains('show')) {
                alert.classList.remove('show');
                setTimeout(() => alert.remove(), 150);
            }
        });
    }, 5000);
});
</script>
@endsection