<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class ActivityTemplateApplication extends Model
{
    use HasFactory;

    protected $table = 'activity_template_applications';

    protected $fillable = [
        'activity_id',
        'template_id',
        'start_date',
        'end_date',
        'customizations',
        'status',
        'sessions_generated'
    ];

    protected $casts = [
        'customizations' => 'array',
        'start_date' => 'date',
        'end_date' => 'date'
    ];

    /**
     * Get the activity this application belongs to
     */
    public function activity()
    {
        return $this->belongsTo(Activity::class);
    }

    /**
     * Get the template this application uses
     */
    public function template()
    {
        return $this->belongsTo(ActivityScheduleTemplate::class, 'template_id');
    }

    /**
     * Get the sessions generated by this application
     */
    public function sessions()
    {
        return $this->hasMany(ActivitySession::class, 'activity_id', 'activity_id')
                   ->whereBetween('session_date', [$this->start_date, $this->end_date]);
    }

    /**
     * Generate sessions from template
     */
    public function generateSessions()
    {
        if (!$this->template || !$this->activity) {
            return false;
        }

        $sessions = $this->template->generateSessions(
            $this->activity, 
            $this->start_date, 
            $this->customizations ?? []
        );

        if (!empty($sessions)) {
            \DB::table('activity_sessions')->insert($sessions);
            $this->update(['sessions_generated' => count($sessions)]);
            return count($sessions);
        }

        return 0;
    }

    /**
     * Check if application is active
     */
    public function getIsActiveAttribute()
    {
        return $this->status === 'active' && 
               $this->start_date <= now() && 
               $this->end_date >= now();
    }

    /**
     * Get progress percentage
     */
    public function getProgressPercentageAttribute()
    {
        if ($this->start_date > now()) {
            return 0;
        }

        $totalDays = $this->start_date->diffInDays($this->end_date);
        $passedDays = $this->start_date->diffInDays(now());

        return $totalDays > 0 ? min(100, round(($passedDays / $totalDays) * 100)) : 100;
    }
}
